spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      .filter:
        enabled=ture

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}


  jpa:
    database: mysql
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        use-new-id-generator-mappings: false

    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      globally_quoted_identifiers: true

  logging:
    level:
      org.springframework: DEBUG

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    stack.auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
