name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set Yaml
      uses: microsoft/variable-substitution@v1
      with:
        files: ./backend/src/main/resources/application.yml
      env:
        spring.datasource.url: ${{ secrets.RDS_URL }}
        spring.datasource.username: ${{ secrets.RDS_USERNAME }}
        spring.datasource.password: ${{ secrets.RDS_PASSWORD }}
        cloud.aws.s3.bucket: ${{ secrets.BUCKET_NAME }}
        cloud.aws.credentials.accessKey: ${{secrets.AWS_ACCESS_KEY}}
        cloud.aws.credentials.secretKey: ${{secrets.AWS_SECRET_KEY}}

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build
